# SCREEN
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# ASTEROIDS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 20

# COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# PLAYER
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3

# BULLET
BULLET_SPEED = 500
BULLET_RADIUS = 5
