# SCREEN
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# ASTEROIDS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# COLORS
BLACK = (0,0,0)

# PLAYER
PLAYER_RADIUS = 20